import axios from '../../core/axios';

const flats = {
    data : [
        {
            "id": "5df105c6453bf9b74d5da059",
            "number": 148,
            "rooms_count": 0,
            "euro": false,
            "area": "556.29",
            "floor": 20,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 8896589,
            "payment": 7262697,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6a6b38d1419f3f37d",
            "number": 233,
            "rooms_count": 1,
            "euro": true,
            "area": "403.17",
            "floor": 64,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 4428673,
            "payment": 8187874,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6fc28996e3123d4be",
            "number": 146,
            "rooms_count": 2,
            "euro": false,
            "area": "466.38",
            "floor": 44,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 3751565,
            "payment": 2550125,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6cdd0ae042e1cf018",
            "number": 167,
            "rooms_count": 4,
            "euro": true,
            "area": "312.21",
            "floor": 74,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 10731234,
            "payment": 3856510,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6c24c53a83d8a6be0",
            "number": 242,
            "rooms_count": 1,
            "euro": true,
            "area": "674.03",
            "floor": 59,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 10957739,
            "payment": 8678274,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6c7cc4b1ffbadde5d",
            "number": 256,
            "rooms_count": 3,
            "euro": true,
            "area": "599.38",
            "floor": 61,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 10815205,
            "payment": 9212734,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6d49e248dac5ef266",
            "number": 148,
            "rooms_count": 3,
            "euro": true,
            "area": "70.95",
            "floor": 34,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 8130485,
            "payment": 4547614,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c68d280a79ae1e5646",
            "number": 13,
            "rooms_count": 2,
            "euro": false,
            "area": "743.8",
            "floor": 83,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 4355360,
            "payment": 4739939,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c672be5d3f0148c382",
            "number": 273,
            "rooms_count": 1,
            "euro": false,
            "area": "265.79",
            "floor": 92,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 8001182,
            "payment": 4898253,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c68f19d86307fbaec4",
            "number": 270,
            "rooms_count": 1,
            "euro": true,
            "area": "276.13",
            "floor": 79,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 6886862,
            "payment": 9070684,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c61d7df8687faf553d",
            "number": 144,
            "rooms_count": 3,
            "euro": false,
            "area": "428.22",
            "floor": 31,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 4520100,
            "payment": 1240715,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c63aed2067cf3379c1",
            "number": 210,
            "rooms_count": 1,
            "euro": true,
            "area": "781.16",
            "floor": 40,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 8361071,
            "payment": 9367452,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6dd6250d534f3d4f8",
            "number": 169,
            "rooms_count": 3,
            "euro": false,
            "area": "192.51",
            "floor": 69,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 8868124,
            "payment": 7601659,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6e7ac79c0494f2a6c",
            "number": 30,
            "rooms_count": 4,
            "euro": true,
            "area": "868.3",
            "floor": 6,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 3597682,
            "payment": 3748359,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6735ffdb0d84ba17e",
            "number": 244,
            "rooms_count": 3,
            "euro": true,
            "area": "124.92",
            "floor": 21,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 3019672,
            "payment": 4085553,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c683a5164b1f10420e",
            "number": 76,
            "rooms_count": 3,
            "euro": false,
            "area": "730.37",
            "floor": 29,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 6468485,
            "payment": 7142373,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6b9100d76b2b46c14",
            "number": 155,
            "rooms_count": 4,
            "euro": true,
            "area": "801.42",
            "floor": 57,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 11816984,
            "payment": 3427695,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c64d0a8d7e81b6b052",
            "number": 261,
            "rooms_count": 3,
            "euro": true,
            "area": "414.52",
            "floor": 79,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 8283139,
            "payment": 6325829,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c63f4c29ea83319023",
            "number": 1,
            "rooms_count": 1,
            "euro": true,
            "area": "188.21",
            "floor": 92,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 2767913,
            "payment": 3817382,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6605df2141f502162",
            "number": 144,
            "rooms_count": 1,
            "euro": false,
            "area": "858.19",
            "floor": 82,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 5069855,
            "payment": 9006809,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6630acf0ed0b44ab4",
            "number": 73,
            "rooms_count": 0,
            "euro": false,
            "area": "19.87",
            "floor": 24,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 8957778,
            "payment": 2896153,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c69b93f71f779fb558",
            "number": 38,
            "rooms_count": 3,
            "euro": true,
            "area": "666.78",
            "floor": 53,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 7394342,
            "payment": 3913977,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c606aa769c251dc455",
            "number": 42,
            "rooms_count": 1,
            "euro": true,
            "area": "136.02",
            "floor": 23,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 9635387,
            "payment": 1835099,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6a2db0368cdfec263",
            "number": 292,
            "rooms_count": 3,
            "euro": false,
            "area": "720.95",
            "floor": 67,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 11088282,
            "payment": 3168340,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6370547af7f0e122a",
            "number": 83,
            "rooms_count": 0,
            "euro": false,
            "area": "888.61",
            "floor": 3,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 8497330,
            "payment": 7376545,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c63afb3fd6443be520",
            "number": 191,
            "rooms_count": 1,
            "euro": false,
            "area": "334.22",
            "floor": 41,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 8061257,
            "payment": 3103124,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6a9e9aa19df11836c",
            "number": 171,
            "rooms_count": 1,
            "euro": false,
            "area": "757.04",
            "floor": 72,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 2258068,
            "payment": 3166558,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6530183ba7240f074",
            "number": 153,
            "rooms_count": 4,
            "euro": true,
            "area": "388.11",
            "floor": 28,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 10866191,
            "payment": 6952581,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6ca5719aff58dc4f0",
            "number": 6,
            "rooms_count": 1,
            "euro": true,
            "area": "656.68",
            "floor": 57,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 4861059,
            "payment": 1538881,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6ae6b9b4eb314a7e7",
            "number": 212,
            "rooms_count": 4,
            "euro": false,
            "area": "246.96",
            "floor": 80,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 10679861,
            "payment": 7164187,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c69f4bdffc675feb8a",
            "number": 110,
            "rooms_count": 3,
            "euro": true,
            "area": "447.61",
            "floor": 71,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 5179461,
            "payment": 3217138,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6fa49e76c24b02a6e",
            "number": 253,
            "rooms_count": 4,
            "euro": true,
            "area": "689.31",
            "floor": 2,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 8366384,
            "payment": 8754340,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6cc493e738d4572f2",
            "number": 202,
            "rooms_count": 1,
            "euro": true,
            "area": "656.91",
            "floor": 42,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 8486271,
            "payment": 2787873,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6e3b0f51dc5184ede",
            "number": 132,
            "rooms_count": 3,
            "euro": false,
            "area": "478.78",
            "floor": 76,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 4058620,
            "payment": 8624181,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6a8ed1b150c592ec3",
            "number": 187,
            "rooms_count": 2,
            "euro": true,
            "area": "639.25",
            "floor": 50,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 11880958,
            "payment": 4946862,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6d2714c7d95cf0b72",
            "number": 155,
            "rooms_count": 2,
            "euro": false,
            "area": "628.11",
            "floor": 44,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 1666574,
            "payment": 6342954,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c65557d0c2ea4c5f09",
            "number": 68,
            "rooms_count": 1,
            "euro": true,
            "area": "433.91",
            "floor": 57,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 1046640,
            "payment": 2544470,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c686cd4f9b815be00d",
            "number": 133,
            "rooms_count": 3,
            "euro": true,
            "area": "115.36",
            "floor": 6,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 3243657,
            "payment": 7638871,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c681ad7eab3a991265",
            "number": 154,
            "rooms_count": 4,
            "euro": false,
            "area": "433.23",
            "floor": 16,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 4676651,
            "payment": 7659280,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c65096c660bd27d54c",
            "number": 127,
            "rooms_count": 4,
            "euro": false,
            "area": "22.58",
            "floor": 92,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 4136161,
            "payment": 5832355,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6da94e22b75cac764",
            "number": 36,
            "rooms_count": 1,
            "euro": false,
            "area": "19.58",
            "floor": 81,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 10061209,
            "payment": 6034082,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c646216e2a042c69a1",
            "number": 93,
            "rooms_count": 1,
            "euro": true,
            "area": "644.56",
            "floor": 1,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 11139210,
            "payment": 4525722,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c680ed760343b05512",
            "number": 43,
            "rooms_count": 0,
            "euro": true,
            "area": "73.22",
            "floor": 52,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 1658541,
            "payment": 9878626,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6af3d174642c68ac8",
            "number": 137,
            "rooms_count": 4,
            "euro": true,
            "area": "789.81",
            "floor": 27,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 4992740,
            "payment": 6317354,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c680df245b67e89c6d",
            "number": 217,
            "rooms_count": 4,
            "euro": true,
            "area": "692.63",
            "floor": 99,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 11724963,
            "payment": 6660547,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6e20f6249935b92bd",
            "number": 279,
            "rooms_count": 4,
            "euro": true,
            "area": "436.49",
            "floor": 78,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 8547089,
            "payment": 1132084,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6b3fb80c8b4c4bdc4",
            "number": 63,
            "rooms_count": 1,
            "euro": true,
            "area": "83.97",
            "floor": 55,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 6062174,
            "payment": 4106766,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c62951783dce9df3d8",
            "number": 76,
            "rooms_count": 0,
            "euro": true,
            "area": "74.6",
            "floor": 4,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 10577506,
            "payment": 3362287,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6fa67935a4fc8b81d",
            "number": 160,
            "rooms_count": 1,
            "euro": true,
            "area": "565.08",
            "floor": 74,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 8443972,
            "payment": 7561876,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c69d6b192800e40021",
            "number": 206,
            "rooms_count": 2,
            "euro": true,
            "area": "662.16",
            "floor": 33,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 1594321,
            "payment": 1713916,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c67ee7152cddbf05e8",
            "number": 298,
            "rooms_count": 1,
            "euro": false,
            "area": "338.65",
            "floor": 5,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 2260964,
            "payment": 7211504,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c68980442dda0c87ed",
            "number": 47,
            "rooms_count": 4,
            "euro": false,
            "area": "574.59",
            "floor": 20,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 9513710,
            "payment": 8890304,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c623394ccd364c3b08",
            "number": 58,
            "rooms_count": 3,
            "euro": true,
            "area": "143.39",
            "floor": 19,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 3281247,
            "payment": 3764378,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6165b497eac32ca58",
            "number": 92,
            "rooms_count": 4,
            "euro": false,
            "area": "288.51",
            "floor": 56,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 6641267,
            "payment": 2623220,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c68e469d3b9ffa0968",
            "number": 217,
            "rooms_count": 4,
            "euro": false,
            "area": "140.15",
            "floor": 25,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 11904541,
            "payment": 5196638,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c67b39c14b7c45bcbb",
            "number": 137,
            "rooms_count": 0,
            "euro": false,
            "area": "270.71",
            "floor": 40,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 5674566,
            "payment": 5790298,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c69ca3cf42562fd6b6",
            "number": 226,
            "rooms_count": 1,
            "euro": false,
            "area": "321.05",
            "floor": 36,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 1072065,
            "payment": 2925467,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c63d426866cb7602af",
            "number": 295,
            "rooms_count": 2,
            "euro": false,
            "area": "646.77",
            "floor": 71,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 2003425,
            "payment": 4912837,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c66d410af54cc10aa5",
            "number": 1,
            "rooms_count": 3,
            "euro": false,
            "area": "574.5",
            "floor": 10,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 8287051,
            "payment": 5830061,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c61a5573b9f4ffccef",
            "number": 239,
            "rooms_count": 3,
            "euro": true,
            "area": "626.12",
            "floor": 12,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 3544702,
            "payment": 9724047,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6a89d3e935ce2a6b6",
            "number": 6,
            "rooms_count": 3,
            "euro": false,
            "area": "473.76",
            "floor": 29,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 5299619,
            "payment": 214397,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c608488c0b428619b8",
            "number": 76,
            "rooms_count": 4,
            "euro": false,
            "area": "18.36",
            "floor": 29,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 5232680,
            "payment": 3171537,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c693126792e4a4e91e",
            "number": 225,
            "rooms_count": 1,
            "euro": true,
            "area": "267.71",
            "floor": 89,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 9604620,
            "payment": 4005554,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6dff8fc8f6fc65117",
            "number": 154,
            "rooms_count": 4,
            "euro": true,
            "area": "623.79",
            "floor": 22,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 6745138,
            "payment": 9033346,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6aa2ea81f773217f3",
            "number": 231,
            "rooms_count": 4,
            "euro": false,
            "area": "777.89",
            "floor": 65,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 10809089,
            "payment": 2047583,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c61377f6740cfc6716",
            "number": 171,
            "rooms_count": 0,
            "euro": true,
            "area": "301.92",
            "floor": 54,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 8734223,
            "payment": 6057967,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c68f2701e479c4271f",
            "number": 43,
            "rooms_count": 2,
            "euro": true,
            "area": "118.83",
            "floor": 49,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 11617875,
            "payment": 7164081,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6fc405dda3d21ad51",
            "number": 66,
            "rooms_count": 2,
            "euro": true,
            "area": "199.79",
            "floor": 51,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 3930429,
            "payment": 1119304,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c66eb614c2f6bf8d24",
            "number": 17,
            "rooms_count": 3,
            "euro": true,
            "area": "728.88",
            "floor": 51,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 2402746,
            "payment": 5692581,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c681fbb81e0e46f1fb",
            "number": 241,
            "rooms_count": 3,
            "euro": true,
            "area": "796.27",
            "floor": 37,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 1245947,
            "payment": 244067,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c675859274cf9c9538",
            "number": 114,
            "rooms_count": 0,
            "euro": true,
            "area": "872.59",
            "floor": 40,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 6397191,
            "payment": 7631485,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c60cd4bcd0bbd7a757",
            "number": 263,
            "rooms_count": 4,
            "euro": false,
            "area": "761.21",
            "floor": 30,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 3455494,
            "payment": 962940,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c697dc270de285a6ef",
            "number": 290,
            "rooms_count": 3,
            "euro": true,
            "area": "413.34",
            "floor": 72,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 11780552,
            "payment": 6467177,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c602af97dc297ebaad",
            "number": 225,
            "rooms_count": 4,
            "euro": true,
            "area": "302.59",
            "floor": 84,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 3341961,
            "payment": 7362132,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c68d8dfaef86afdc7b",
            "number": 99,
            "rooms_count": 0,
            "euro": false,
            "area": "479.05",
            "floor": 53,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 5432931,
            "payment": 5501264,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6310c797aa33d19e5",
            "number": 238,
            "rooms_count": 4,
            "euro": true,
            "area": "844.26",
            "floor": 43,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 7657789,
            "payment": 2499082,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c65f78639a8fa132d7",
            "number": 27,
            "rooms_count": 0,
            "euro": false,
            "area": 520,
            "floor": 64,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 9554425,
            "payment": 9954865,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6f20dc0bf774e2895",
            "number": 44,
            "rooms_count": 0,
            "euro": false,
            "area": "677.05",
            "floor": 29,
            "building": 311,
            "period": "1 кв. 2020",
            "price": 9645307,
            "payment": 2489439,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6e3bdda61dec238ae",
            "number": 291,
            "rooms_count": 2,
            "euro": true,
            "area": "371.02",
            "floor": 61,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 4261372,
            "payment": 9068566,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6fda76d9ac4e7e248",
            "number": 231,
            "rooms_count": 2,
            "euro": true,
            "area": "17.62",
            "floor": 18,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 5383967,
            "payment": 2995534,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c67224fecf6b0a0237",
            "number": 215,
            "rooms_count": 4,
            "euro": true,
            "area": 398,
            "floor": 58,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 6757817,
            "payment": 1189469,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6dde59fdb535f2506",
            "number": 141,
            "rooms_count": 0,
            "euro": true,
            "area": "227.87",
            "floor": 39,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 8147364,
            "payment": 924874,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6b2fcfca52cc7a8e3",
            "number": 32,
            "rooms_count": 1,
            "euro": true,
            "area": "290.8",
            "floor": 46,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 4506808,
            "payment": 8790181,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c60485eb81555f01ba",
            "number": 181,
            "rooms_count": 1,
            "euro": false,
            "area": "526.96",
            "floor": 14,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 3056372,
            "payment": 685848,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6df96b342d63aecf7",
            "number": 102,
            "rooms_count": 3,
            "euro": false,
            "area": "611.1",
            "floor": 45,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 10623593,
            "payment": 5140295,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6eb8ab1c385cb06b0",
            "number": 55,
            "rooms_count": 2,
            "euro": true,
            "area": "259.8",
            "floor": 93,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 10602081,
            "payment": 2357018,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6e3dffaf1e392b490",
            "number": 14,
            "rooms_count": 4,
            "euro": true,
            "area": "169.32",
            "floor": 5,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 11331983,
            "payment": 5516838,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c679f2c1e8ffa79368",
            "number": 108,
            "rooms_count": 1,
            "euro": true,
            "area": "755.66",
            "floor": 32,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 9306434,
            "payment": 9291839,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c64e5a7c545ef3c448",
            "number": 27,
            "rooms_count": 4,
            "euro": false,
            "area": "870.35",
            "floor": 82,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 9474415,
            "payment": 8183469,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6c5c8bf487e8e7434",
            "number": 47,
            "rooms_count": 2,
            "euro": true,
            "area": "435.32",
            "floor": 44,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 4737198,
            "payment": 8254639,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c685c132138049940b",
            "number": 261,
            "rooms_count": 0,
            "euro": true,
            "area": "88.09",
            "floor": 3,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 6653482,
            "payment": 3261354,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6a520b8f849506b3e",
            "number": 26,
            "rooms_count": 3,
            "euro": false,
            "area": "115.56",
            "floor": 75,
            "building": 314,
            "period": "1 кв. 2020",
            "price": 11371818,
            "payment": 1145110,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6546442788d2e7ef5",
            "number": 103,
            "rooms_count": 0,
            "euro": true,
            "area": "439.76",
            "floor": 21,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 11475164,
            "payment": 8210826,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c67b96477361c45762",
            "number": 232,
            "rooms_count": 2,
            "euro": false,
            "area": "581.98",
            "floor": 48,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 10407232,
            "payment": 9682750,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c64d3144debafc4f66",
            "number": 80,
            "rooms_count": 0,
            "euro": true,
            "area": "374.24",
            "floor": 67,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 6578158,
            "payment": 8826218,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6b1e3972ac50a5b5d",
            "number": 256,
            "rooms_count": 1,
            "euro": true,
            "area": "232.11",
            "floor": 89,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 4086291,
            "payment": 6245727,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c61ce3f3f813ef3596",
            "number": 19,
            "rooms_count": 2,
            "euro": true,
            "area": "847.86",
            "floor": 90,
            "building": 309,
            "period": "1 кв. 2020",
            "price": 2093021,
            "payment": 1291162,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c6b64ad826e5935067",
            "number": 70,
            "rooms_count": 1,
            "euro": false,
            "area": "652.13",
            "floor": 11,
            "building": 310,
            "period": "1 кв. 2020",
            "price": 10780552,
            "payment": 9301383,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c641f00dac88d93d6a",
            "number": 2,
            "rooms_count": 4,
            "euro": false,
            "area": "454.24",
            "floor": 59,
            "building": 308,
            "period": "1 кв. 2020",
            "price": 6084282,
            "payment": 9419419,
            "finish": false,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        },
        {
            "id": "5df105c65ff2ed81dd353543",
            "number": 132,
            "rooms_count": 3,
            "euro": true,
            "area": "117.4",
            "floor": 46,
            "building": 307,
            "period": "1 кв. 2020",
            "price": 9860423,
            "payment": 8332025,
            "finish": true,
            "planImg": "/img/apartment-plan.svg",
            "buildingImg": "/img/apartment-genplan.svg",
            "floorImg": "/img/apartment-floor.svg"
        }
    ]
};

export default {
    getAll: () => {
        return new Promise((resolve, reject) =>{
            setTimeout(() => {
                resolve(flats)
            }, 1600);
        });
        // return axios.get("/apartments")
    }
}